# Generated by Django 4.2 on 2023-04-21 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en proceso', 'En proceso'), ('solucionado', 'Solucionado')], max_length=20, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_prioridad', models.AutoField(primary_key=True, serialize=False)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=20, verbose_name='Prioridad')),
            ],
        ),
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id_programador', models.AutoField(primary_key=True, serialize=False)),
                ('correo_programador', models.EmailField(max_length=254)),
                ('nombre_programador', models.CharField(max_length=255, verbose_name='Nombre del programador')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre del proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo_usuario', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteBug',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('reporte', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='database.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id_bug', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.estado', verbose_name='Estado')),
                ('prioridad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.prioridad', verbose_name='Prioridad')),
                ('programador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.programador', verbose_name='Programador')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.proyecto', verbose_name='Proyecto')),
                ('reportes', models.ManyToManyField(related_name='bugs', to='database.reportebug', verbose_name='Reportes')),
            ],
        ),
    ]
