# Generated by Django 4.2 on 2023-04-28 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id_bug', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='Titulo del bug')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=20, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('en proceso', 'En proceso'), ('solucionado', 'Solucionado')], max_length=20, verbose_name='Estado')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo en el proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Programador',
            fields=[
                ('id_programador', models.AutoField(primary_key=True, serialize=False)),
                ('correo_programador', models.EmailField(max_length=254)),
                ('nombre_programador', models.CharField(max_length=255, verbose_name='Nombre del programador')),
            ],
            options={
                'verbose_name_plural': 'Programadores',
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(max_length=255, verbose_name='Nombre del proyecto')),
                ('programadores', models.ManyToManyField(through='database.Cargo', to='database.programador')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('correo_usuario', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteBug',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='titulo del reporte')),
                ('reporte', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('correo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='database.usuario')),
                ('id_bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.bug', verbose_name='Bug')),
                ('id_proyecto', models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='database.proyecto', verbose_name='Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_programador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.programador'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.proyecto'),
        ),
        migrations.AddField(
            model_name='bug',
            name='id_programador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.programador', verbose_name='Programador'),
        ),
        migrations.AddField(
            model_name='bug',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.proyecto', verbose_name='Proyecto'),
        ),
    ]
