# Generated by Django 4.2 on 2023-05-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='estado',
            field=models.CharField(choices=[('ASIGNADO', 'bug recien asignado'), ('EN PROCESO', 'bug esta proceso de revisión'), ('SOLUCIONADO', 'bug solucionado')], max_length=50, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'bug de baja prioridad'), ('MEDIA', 'bug de media prioridad'), ('ALTA', 'bug de alta prioridad'), ('URGENTE', 'bug de urgente prioridad')], max_length=50, verbose_name='prioridad'),
        ),
        migrations.AlterField(
            model_name='reportebug',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'reporte del bug esta en revisión'), ('APROBADO', 'reporte del bug fue aprobado'), ('DESAPROBADO', 'reporte del bug fue desaprobado')], default=('PENDIENTE', 'reporte del bug esta en revisión'), max_length=50, verbose_name='estado del reporte'),
        ),
    ]
