# Generated by Django 4.2 on 2023-06-01 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportebug',
            old_name='correo_usuario',
            new_name='id_usuario',
        ),
    ]
