# Generated by Django 4.2 on 2023-05-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportebug',
            name='correo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.usuario', verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='Reasignacion',
            fields=[
                ('id_avance', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reasignacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('id_bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.bug', verbose_name='Bug')),
                ('id_programador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.programador', verbose_name='Programador')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('id_bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.bug', verbose_name='Bug')),
                ('id_programador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.programador', verbose_name='Programador')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database.usuario', verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id_imagen', models.AutoField(primary_key=True, serialize=False)),
                ('id_reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.reportebug', verbose_name='reporte')),
            ],
        ),
        migrations.CreateModel(
            name='Avances',
            fields=[
                ('id_avance', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255, verbose_name='titulo del reporte')),
                ('descripcion', models.TextField()),
                ('fecha_avance', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('id_bug', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.bug', verbose_name='Bug')),
            ],
        ),
    ]
