# Generated by Django 4.2.1 on 2023-06-21 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasignacion',
            name='id_programador_final',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programadores_reasignados', related_query_name='programador_reasignado', to='database.programador', verbose_name='programador reasignado'),
        ),
    ]
