# Generated by Django 4.2 on 2023-05-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_reportebug_correo_usuario_reasignacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='database/images/default.jpg', upload_to='database/images'),
        ),
    ]
