# Generated by Django 4.2 on 2023-05-28 03:26

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_bug_estado_alter_bug_prioridad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='database/images/default.jpg', upload_to=database.models.custom_upload_to),
        ),
    ]
