# Generated by Django 4.2 on 2023-06-01 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_rename_correo_usuario_reportebug_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha del caso'),
        ),
    ]
