# Generated by Django 4.2 on 2023-04-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_bug_reportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportebug',
            name='titulo',
            field=models.CharField(default='a', max_length=255, verbose_name='titulo del reporte'),
            preserve_default=False,
        ),
    ]
