# Generated by Django 4.2 on 2023-04-28 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_reportebug_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportebug',
            name='id_proyecto',
            field=models.ForeignKey(db_column='id_proyecto', on_delete=django.db.models.deletion.CASCADE, to='database.proyecto', verbose_name='Proyecto'),
        ),
    ]
