# Generated by Django 4.2 on 2023-04-25 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_remove_bug_reportes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportebug',
            old_name='usuario',
            new_name='correo_usuario',
        ),
    ]
