# Generated by Django 4.2.1 on 2023-06-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_imagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasignacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'reasignación pendiente'), ('APROBADO', 'reasignación aprobada'), ('DESAPROBADO', 'reasignación desaprobada')], default='PENDIENTE', max_length=50, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reportebug',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'reporte del bug esta en revisión'), ('APROBADO', 'reporte del bug fue aprobado'), ('DESAPROBADO', 'reporte del bug fue desaprobado')], default='PENDIENTE', max_length=50, verbose_name='estado del reporte'),
        ),
    ]
