# Generated by Django 4.2 on 2023-05-23 02:39

import database.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_imagen_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(default='database/images/default.jpg', upload_to=database.models.custom_upload_to),
        ),
    ]
