# Generated by Django 4.2 on 2023-04-23 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_reportebug_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoEn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo en el proyecto')),
                ('id_programador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.programador')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='reportebug',
            name='id_bug',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='database.bug', verbose_name='Bug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bug',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('en proceso', 'En proceso'), ('solucionado', 'Solucionado')], max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], max_length=20, verbose_name='Prioridad'),
        ),
        migrations.DeleteModel(
            name='Estado',
        ),
        migrations.DeleteModel(
            name='Prioridad',
        ),
    ]
