# Generated by Django 4.2 on 2023-04-23 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_trabajoen_reportebug_id_bug_alter_bug_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportebug',
            name='id_bug',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.bug', verbose_name='Bug'),
        ),
    ]
