# Generated by Django 4.2 on 2023-05-28 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_bug_fecha_reporte_alter_reportebug_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bug',
            name='estado',
            field=models.CharField(choices=[('ASIGNADO', 'bug recien asignado'), ('EN PROCESO', 'bug esta proceso de revisión'), ('SOLUCIONADO', 'bug solucionado')], default=('ASIGNADO', 'bug recien asignado'), max_length=50, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='reportebug',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'pendiente'), ('APROBADO', 'aprobado'), ('DESAPROBADO', 'desaprobado')], default=('PENDIENTE', 'pendiente'), max_length=50, verbose_name='estado del reporte'),
        ),
    ]
