# Generated by Django 4.2 on 2023-05-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_bug_estado_alter_reportebug_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasignacion',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'reasignación pendiente'), ('APROBADO', 'reasignación aprobada'), ('DESAPROBADO', 'reasignación desaprobada')], default=('PENDIENTE', 'reasignación pendiente'), max_length=50, verbose_name='estado de la reasignación'),
        ),
    ]
