# Generated by Django 4.2 on 2023-04-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_alter_reportebug_id_bug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='programador',
            new_name='id_programador',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='proyecto',
            new_name='id_proyecto',
        ),
        migrations.RenameField(
            model_name='reportebug',
            old_name='usuario',
            new_name='correo_usuario',
        ),
    ]
