# Generated by Django 4.2 on 2023-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_programador_bug_id_programador_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrabajoEn',
            new_name='Cargo',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='id_programador',
            new_name='programador',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='id_proyecto',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_programador',
            new_name='programador',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='id_proyecto',
            new_name='proyecto',
        ),
        migrations.RenameField(
            model_name='reportebug',
            old_name='id_bug',
            new_name='bug',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='programadores',
            field=models.ManyToManyField(through='database.Cargo', to='database.programador'),
        ),
    ]
