# Generated by Django 4.2 on 2023-05-31 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_reasignacion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportebug',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'reporte en estado pendiente'), ('APROBADO', 'reporte aprobado'), ('DESAPROBADO', 'reporte desaprobado')], default='PENDIENTE', max_length=50, verbose_name='estado del reporte'),
        ),
    ]
