# Generated by Django 4.2 on 2023-04-26 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_rename_trabajoen_cargo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programador',
            options={'verbose_name_plural': 'Programadores'},
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='programador',
            new_name='id_programador',
        ),
        migrations.RenameField(
            model_name='bug',
            old_name='proyecto',
            new_name='id_proyecto',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='programador',
            new_name='id_programador',
        ),
        migrations.RenameField(
            model_name='cargo',
            old_name='proyecto',
            new_name='id_proyecto',
        ),
        migrations.RenameField(
            model_name='reportebug',
            old_name='bug',
            new_name='id_bug',
        ),
        migrations.AddField(
            model_name='bug',
            name='fecha_reporte',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de reporte'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bug',
            name='titulo',
            field=models.CharField(default='a', max_length=255, verbose_name='Titulo del bug'),
            preserve_default=False,
        ),
    ]
