# Generated by Django 4.2 on 2023-04-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_rename_usuario_reportebug_correo_usuario'),
        ('database', '0008_alter_programador_options_and_more'),
    ]

    operations = [
    ]
