# Generated by Django 4.2 on 2023-04-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_programador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportebug',
            name='estado',
            field=models.CharField(choices=[('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
