# Generated by Django 4.2 on 2023-04-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_reportebug_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportebug',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('desaprobado', 'Desaprobado')], default='Pendiente', max_length=20, verbose_name='Estado'),
        ),
    ]
