# Generated by Django 4.2 on 2023-04-28 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_alter_reportebug_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(max_length=255, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id_programador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.programador', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='id_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='programador',
            name='correo_programador',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='programador',
            name='nombre_programador',
            field=models.CharField(max_length=255, verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nombre_proyecto',
            field=models.CharField(max_length=255, verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='reportebug',
            name='correo_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='database.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo_usuario',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False, verbose_name='Email'),
        ),
    ]
