# Generated by Django 4.2 on 2023-04-28 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_merge_20230427_1420'),
        ('database', '0010_alter_reportebug_estado'),
    ]

    operations = [
    ]
