# Generated by Django 4.2 on 2023-04-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_reportebug_id_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportebug',
            name='id_proyecto',
        ),
    ]
